// +build !ios

package ui

/*
#cgo CFLAGS: -pipe -O2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC -DQT_NO_DEBUG -DQT_DESIGNER_LIB -DQT_UIPLUGIN_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_XML_LIB -DQT_CORE_LIB
#cgo CXXFLAGS: -pipe -stdlib=libc++ -O2 -std=gnu++11 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC -DQT_NO_DEBUG -DQT_DESIGNER_LIB -DQT_UIPLUGIN_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_XML_LIB -DQT_CORE_LIB
#cgo CXXFLAGS: -I../../internal -I. -I/usr/local/Cellar/qt/5.11.1/lib/QtDesigner.framework/Headers -I/usr/local/Cellar/qt/5.11.1/lib/QtUiPlugin.framework/Headers -I/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.11.1/lib/QtMultimedia.framework/Headers/5.11.1 -I/usr/local/Cellar/qt/5.11.1/lib/QtMultimedia.framework/Headers/5.11.1/QtMultimedia -I/usr/local/Cellar/qt/5.11.1/lib/QtMultimedia.framework/Headers -I/usr/local/Cellar/qt/5.11.1/lib/QtQuick.framework/Headers -I/usr/local/Cellar/qt/5.11.1/lib/QtGui.framework/Headers/5.11.1 -I/usr/local/Cellar/qt/5.11.1/lib/QtGui.framework/Headers/5.11.1/QtGui -I/usr/local/Cellar/qt/5.11.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.11.1/lib/QtQml.framework/Headers -I/usr/local/Cellar/qt/5.11.1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.11.1/lib/QtDBus.framework/Headers -I/usr/local/Cellar/qt/5.11.1/lib/QtXml.framework/Headers -I/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/5.11.1 -I/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/5.11.1/QtCore -I/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/5.11.1/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.11.1/lib
#cgo LDFLAGS: -stdlib=libc++ -headerpad_max_install_names -arch x86_64 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wl,-rpath,@executable_path/Frameworks
#cgo LDFLAGS:  -F/usr/local/Cellar/qt/5.11.1/lib -framework QtDesigner -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtXml -framework QtMultimedia -framework QtNetwork -framework QtQuick -framework QtQml -framework QtDBus -framework OpenGL -framework AGL
#cgo CFLAGS: -Wno-unused-parameter -Wno-unused-variable -Wno-return-type
#cgo CXXFLAGS: -Wno-unused-parameter -Wno-unused-variable -Wno-return-type
*/
import "C"
